### PR TITLE
Fixed build with exiv2-0.27.1

### PR DESCRIPTION
**Pull request by sikmir**
```bash
$ make CFLAGS=-DENABLE_NLS GTK=3
...
exif-gps.cpp: In function 'char* ReadExifDate(const char*, int*)':
exif-gps.cpp:103:18: error: 'Error' in namespace 'Exiv2' does not name a type
  } catch (Exiv2::Error& e) {
                  ^~~~~
exif-gps.cpp: In function 'char* ReadExifData(const char*, double*, double*, double*, int*)':
exif-gps.cpp:160:18: error: 'Error' in namespace 'Exiv2' does not name a type
  } catch (Exiv2::Error& e) {
                  ^~~~~
exif-gps.cpp: In function 'char* ReadGPSTimestamp(const char*, char*, char*, int*)':
exif-gps.cpp:298:18: error: 'Error' in namespace 'Exiv2' does not name a type
  } catch (Exiv2::Error& e) {
                  ^~~~~
exif-gps.cpp: In function 'int WriteGPSData(const char*, const GPSPoint*, const char*, int, int)':
exif-gps.cpp:469:18: error: 'Error' in namespace 'Exiv2' does not name a type
  } catch (Exiv2::Error& e) {
                  ^~~~~
exif-gps.cpp:619:18: error: 'Error' in namespace 'Exiv2' does not name a type
  } catch (Exiv2::Error& e) {
                  ^~~~~
exif-gps.cpp: In function 'int WriteFixedDatestamp(const char*, time_t)':
exif-gps.cpp:649:18: error: 'Error' in namespace 'Exiv2' does not name a type
  } catch (Exiv2::Error& e) {
                  ^~~~~
exif-gps.cpp:684:18: error: 'Error' in namespace 'Exiv2' does not name a type
  } catch (Exiv2::Error& e) {
                  ^~~~~
exif-gps.cpp: In function 'int RemoveGPSExif(const char*, int, int)':
exif-gps.cpp:711:18: error: 'Error' in namespace 'Exiv2' does not name a type
  } catch (Exiv2::Error& e) {
                  ^~~~~
exif-gps.cpp:737:19: error: 'Error' in namespace 'Exiv2' does not name a type
   } catch (Exiv2::Error& e) {
                   ^~~~~
make: *** [Makefile:53: exif-gps.o] Error 1
```

### CODE REVIEW

**Comment by dfandrich** [comment]
Do you know if this also works for earlier exiv2 versions?

**Comment by sikmir** [comment]
Yes, it works. I've tested with exiv2-0.25.

**Comment by dfandrich** [comment]
I just tried it on exiv2 0.18 and it didn't work (it doesn't supply exiv2.hpp).
Since this version is still supported in RHEL6 for at least another year, and
since gpscorrelate doesn't depend on anything in newer versions, it would be
nice if it could remain compatible. Can you find a way to make it work? Maybe
by including error.hpp instead (that still works on 0.18)?

**Comment by sikmir** [comment]
> Can you find a way to make it work? Maybe by including error.hpp instead (that still works on 0.18)?

OK, updated.

**Comment by dfandrich** [comment]
Thanks!
